name: scheduled run main.py

on:
  schedule:
    - cron: '0 0 * * 2,4' # At 8AM for GMT+8, 12AM for UTC, every Tue and Thu
  # push:
  #   branches:
  #     - main
  #     - master
    
env:
  email: ${{ secrets.EMAIL }}
  app_pass: ${{ secrets.APP_PASS }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get current time
        id: current-time
        uses: josStorer/get-current-time@v2

      - name: execute py script
        run: python main.py

      - name: commit files
        run: |
          git config --local user.email "limsienlong@gmail.com"
          git config --local user.name "sienlonglim"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Weekly run" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master 
